import type { LocalModel, ModelFamily } from "@/types";

export const MODEL_CATALOG: LocalModel[] = [
  // Small
  {
    id: "llama-3.2-3b",
    name: "Llama 3.2 3B",
    paramsB: 3,
    family: "llama",
    useCases: ["chat"],
    ollamaTag: "llama3.2:3b",
    description: "Compact Meta model for everyday chat",
  },
  {
    id: "gemma-2-2b",
    name: "Gemma 2 2B",
    paramsB: 2,
    family: "gemma",
    useCases: ["chat"],
    ollamaTag: "gemma2:2b",
    description: "Google's lightweight general-purpose model",
  },
  {
    id: "phi-3-mini",
    name: "Phi-3 Mini 3.8B",
    paramsB: 3.8,
    family: "phi",
    useCases: ["chat", "coding"],
    ollamaTag: "phi3:mini",
    description: "Microsoft's efficient small model",
  },
  {
    id: "qwen2.5-3b",
    name: "Qwen2.5 3B",
    paramsB: 3,
    family: "qwen",
    useCases: ["chat", "coding"],
    ollamaTag: "qwen2.5:3b",
    description: "Alibaba's multilingual small model",
  },
  {
    id: "llama-3.2-1b",
    name: "Llama 3.2 1B",
    paramsB: 1,
    family: "llama",
    useCases: ["chat"],
    ollamaTag: "llama3.2:1b",
    description: "Ultra-light model for low-end hardware",
  },

  // Embedding
  {
    id: "nomic-embed-text",
    name: "Nomic Embed Text",
    paramsB: 0.14,
    family: "nomic",
    useCases: ["embedding"],
    ollamaTag: "nomic-embed-text",
    description: "Popular open embedding model for RAG and semantic search",
  },
  {
    id: "mxbai-embed-large",
    name: "MxBai Embed Large",
    paramsB: 0.34,
    family: "mxbai",
    useCases: ["embedding"],
    ollamaTag: "mxbai-embed-large",
    description: "High-quality embeddings from Mixedbread AI",
  },
  {
    id: "bge-large",
    name: "BGE Large",
    paramsB: 0.34,
    family: "bge",
    useCases: ["embedding"],
    ollamaTag: "bge-large",
    description: "BAAI general-purpose embedding model",
  },
  {
    id: "snowflake-arctic-embed",
    name: "Snowflake Arctic Embed",
    paramsB: 0.11,
    family: "snowflake",
    useCases: ["embedding"],
    ollamaTag: "snowflake-arctic-embed",
    description: "Compact Snowflake embedding model for retrieval",
  },

  // Medium
  {
    id: "llama-3.1-8b",
    name: "Llama 3.1 8B",
    paramsB: 8,
    family: "llama",
    useCases: ["chat", "coding"],
    ollamaTag: "llama3.1:8b",
    description: "Popular all-rounder for local inference",
  },
  {
    id: "mistral-7b",
    name: "Mistral 7B",
    paramsB: 7,
    family: "mistral",
    useCases: ["chat", "coding"],
    ollamaTag: "mistral:7b",
    description: "Fast, capable 7B model",
  },
  {
    id: "qwen2.5-7b",
    name: "Qwen2.5 7B",
    paramsB: 7,
    family: "qwen",
    useCases: ["chat", "coding"],
    ollamaTag: "qwen2.5:7b",
    description: "Strong multilingual 7B model",
  },
  {
    id: "deepseek-r1-distill-7b",
    name: "DeepSeek R1 Distill 7B",
    paramsB: 7,
    family: "deepseek",
    useCases: ["reasoning", "coding"],
    ollamaTag: "deepseek-r1:7b",
    description: "Reasoning-focused distilled model",
  },
  {
    id: "gemma-2-9b",
    name: "Gemma 2 9B",
    paramsB: 9,
    family: "gemma",
    useCases: ["chat", "coding"],
    ollamaTag: "gemma2:9b",
    description: "Google's balanced 9B model",
  },
  {
    id: "phi-3-medium",
    name: "Phi-3 Medium 14B",
    paramsB: 14,
    family: "phi",
    useCases: ["chat", "coding", "reasoning"],
    ollamaTag: "phi3:medium",
    description: "Microsoft's mid-size capable model",
  },
  {
    id: "qwen2.5-14b",
    name: "Qwen2.5 14B",
    paramsB: 14,
    family: "qwen",
    useCases: ["chat", "coding", "reasoning"],
    ollamaTag: "qwen2.5:14b",
    description: "Strong 14B general model",
  },
  {
    id: "llama-3.2-vision-11b",
    name: "Llama 3.2 Vision 11B",
    paramsB: 11,
    family: "llama",
    useCases: ["vision", "chat"],
    ollamaTag: "llama3.2-vision:11b",
    description: "Multimodal vision + text model",
    minRamGB: 12,
  },

  // Large
  {
    id: "qwen2.5-32b",
    name: "Qwen2.5 32B",
    paramsB: 32,
    family: "qwen",
    useCases: ["chat", "coding", "reasoning"],
    ollamaTag: "qwen2.5:32b",
    description: "High-quality 32B model for powerful GPUs",
    minRamGB: 24,
  },
  {
    id: "deepseek-v2-16b",
    name: "DeepSeek V2 16B",
    paramsB: 16,
    family: "deepseek",
    useCases: ["chat", "coding", "reasoning"],
    ollamaTag: "deepseek-v2:16b",
    description: "Efficient MoE-style architecture",
    minRamGB: 16,
  },
  {
    id: "mixtral-8x7b",
    name: "Mixtral 8x7B",
    paramsB: 47,
    activeParamsB: 13,
    family: "mistral",
    useCases: ["chat", "coding", "reasoning"],
    ollamaTag: "mixtral:8x7b",
    description: "MoE model, 47B total, ~13B active",
    minRamGB: 32,
  },
  {
    id: "llama-3.1-70b",
    name: "Llama 3.1 70B",
    paramsB: 70,
    family: "llama",
    useCases: ["chat", "coding", "reasoning"],
    ollamaTag: "llama3.1:70b",
    description: "Flagship open model, needs 48GB+ VRAM at Q4",
    minRamGB: 48,
  },
  {
    id: "qwen2.5-72b",
    name: "Qwen2.5 72B",
    paramsB: 72,
    family: "qwen",
    useCases: ["chat", "coding", "reasoning"],
    ollamaTag: "qwen2.5:72b",
    description: "Top-tier Qwen model for high-end hardware",
    minRamGB: 48,
  },
  {
    id: "deepseek-r1-32b",
    name: "DeepSeek R1 32B",
    paramsB: 32,
    family: "deepseek",
    useCases: ["reasoning", "coding"],
    ollamaTag: "deepseek-r1:32b",
    description: "Advanced reasoning model",
    minRamGB: 24,
  },
  {
    id: "codestral-22b",
    name: "Codestral 22B",
    paramsB: 22,
    family: "mistral",
    useCases: ["coding"],
    ollamaTag: "codestral:22b",
    description: "Mistral's code-specialized model",
    minRamGB: 16,
  },
  {
    id: "llama-3.3-70b",
    name: "Llama 3.3 70B",
    paramsB: 70,
    family: "llama",
    useCases: ["chat", "coding", "reasoning"],
    ollamaTag: "llama3.3:70b",
    description: "Latest Llama flagship",
    minRamGB: 48,
  },
  {
    id: "mistral-nemo-12b",
    name: "Mistral Nemo 12B",
    paramsB: 12,
    family: "mistral",
    useCases: ["chat", "coding"],
    ollamaTag: "mistral-nemo:12b",
    description: "128K context capable 12B model",
  },
  {
    id: "qwen2.5-coder-7b",
    name: "Qwen2.5 Coder 7B",
    paramsB: 7,
    family: "qwen",
    useCases: ["coding"],
    ollamaTag: "qwen2.5-coder:7b",
    description: "Code-specialized 7B model",
  },
  {
    id: "deepseek-coder-v2-16b",
    name: "DeepSeek Coder V2 16B",
    paramsB: 16,
    family: "deepseek",
    useCases: ["coding"],
    ollamaTag: "deepseek-coder-v2:16b",
    description: "Strong open coding model",
    minRamGB: 12,
  },
  {
    id: "llama-3.1-405b",
    name: "Llama 3.1 405B",
    paramsB: 405,
    family: "llama",
    useCases: ["chat", "reasoning"],
    ollamaTag: "llama3.1:405b",
    description: "Extreme scale, multi-GPU datacenter only",
    minRamGB: 256,
  },
];

export const MODEL_FAMILY_LABELS: Record<ModelFamily, string> = {
  bge: "BGE",
  deepseek: "DeepSeek",
  gemma: "Gemma",
  llama: "Llama",
  mistral: "Mistral",
  mxbai: "MXBAI",
  nomic: "Nomic",
  phi: "Phi",
  qwen: "Qwen",
  snowflake: "Snowflake",
};

export const MODEL_FAMILIES = [
  ...new Set(MODEL_CATALOG.map((m) => m.family)),
].sort() as ModelFamily[];
